name: massconfusion
favicon: null
layout_spectrum: 0.24158
typography_spectrum: 0.64913
title: mass confusion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0b'
    - '#282828'
    - '#c0c0c0'
    - '#969696'
    - '#f8f8f8'
  brandStrength: 1
  lightness: 1
  saturation: 0.051672423956915736
  rhythmicContrast: 0
purpose: []
