typography_spectrum: 0.64913
color:
  brandColors:
    - '#0b0b0b'
    - '#282828'
    - '#c0c0c0'
    - '#969696'
    - '#f8f8f8'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: massconfusion
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: the illest alive
    url: 'http://mass-confusion.com'
    type: external
favicon: null
title: mass confusion
purpose: []
